// /app/layout.tsx
import "@fontsource/kranky"
import "@fontsource/ovo"
// Supports weights 400-700
import "@fontsource-variable/lora"
// Supports weights 300-700
import "@fontsource-variable/cormorant"
import type { Metadata } from "next"

import "./globals.css"
import Header from "@/components/___c___layout__header/Header"
import Footer from "@/components/___c___layout__footer/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <Header />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
